{% set name = "meepmeep" %}
{% set version = "0.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meepmeep-{{ version }}.tar.gz
  sha256: 871d37f23fe310f3768478a9a3544d7cea39ebb2f28669cfaf93f34dae9740ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba
    - scipy
    - matplotlib-base
    - semantic_version

test:
  imports:
    - meepmeep
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hpparvi/MeepMeep
  summary: 'Fast Keplerian orbit computation using Taylor series expansions.'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hpparvi
