{% set name = "meepmeep" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/meepmeep-{{ version }}.tar.gz
  sha256: 86b2aaff50f34f06d4740a425ab558d9cb4599950ed2f9415b672940e2c30234

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba
    - scipy
    - matplotlib-base
    - semantic_version

test:
  imports:
    - meepmeep
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/hpparvi/MeepMeep
  summary: 'Fast Keplerian orbit computation using Taylor series expansions.'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hpparvi
